<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IMCHLT128" ignored="0" tests="3" failures="1" timestamp="21 Jun 2018 08:06:55 GMT" time="0.627" errors="0">
  <testcase name="test001" time="0.189" classname="LoginTest"/>
  <testcase name="test003" time="0.007" classname="LoginTest"/>
  <testcase name="test002" time="0.011" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at LoginTest.test002(LoginTest.java:53)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test002 -->
</testsuite>
